log:
  disable_sentry: true

db:
  url: postgres://postgres:postgres@127.0.0.1:5432/postgres?sslmode=disable

listener:
  addr: :8080 # TODO configure and rm this TODO

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: api
  service_port: 80
